version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 3000:80

  n_app:
    build: .
    environment:
      - PORT=6000